language: java
env:
  global:
    # OSSRH_JIRA_USERNAME
    - secure: "r8pToS27zBwMkMO2ZuNz60IfG+vg3h26urXQ7IHSnC5w9K6Gwx8R5L4NRAF3z/Kzczyh+6kfzjAAFcbxUGVABsYMyBf8gw1M9eS0nEK2FZ96hGvqbtDYSRmM6fRe0AWhCOeyIqkRWtfuekhKyGIZTMnDXMPRZo8tlTxjaQkGr5IkG183tAa9/X26FiIg/+ONWhTtLGDgioV/0VN0joMMcamKnhShUBFeXWqhaVVSP/v+iYuEUfPl3igduejgmXiYqtm9YI5fpHOvirGV6TWTlEPJHc+FwVhRKj0kdqJsaYRlCM7x2pkJ6ipyzWCNBIwRyNzlAlWG04yLL4ogFigLceCuB92OFcw/eObG6eZOv4Kj/Nm8pcTLL0gduIQuXaKj6vOsVav82OU4gyObKGCWtztZiCnExpCafj/IZy6W+HUXee6HoEytcCer4tkOuW6O8B9VyRMyxBHRc76wsvyOBGSUb1ui/PCiQAzCSmyOoYG/0y5BkrEE4Oxf0ZNcGj26adcWq86xQqGReIpjufUGa04dhWt7HKHaFrVAabY++KLkwDB01ln+pzsAzHDhQfZIEXeS8E0wS7Oxey1NEZQfHd1vVvhaDwpl2LUCWsWhyiOx9e4alcnmQXxgFCxaQh7aK0nJPU5wrszHz5tSlAGihD/KBJuHrV5wUneDQ0/RNxw="
    # OSSRH_JIRA_PASSWORD
    - secure: "TSMfjgQpQpQlR5FkquUBfGUgcIZwiiNQvzCCVkx1pG0geVlO4cLX2W2/GPPyxEAE21w8YissSwXbBCuExHCgqfl3txtagX+745Dm1dSl3Q3n63fz+vhIVwi2fMy7AeAfGPvtpV8BC3kbQg0oIKk26LC7S6/4HuN6adCmhvJHUTaEYwI3W4xCj2qGfs1BWBt7EWGUMdLgGJN2nZO9rln3nRMEcWLqrywKC/GZhMttjv0lXKMa4lwlG9IL17upVJ6X584B5aZDWj77VUcIf74Qwjbyv3tbTBoi9Usb7XDuPjNi4fM//RSaeIu2wcCyjNgwZguIkQLeZMfzdGjy/c8e+f/jqTk4dI4560LQTHmXXUk8nCAvsY0XRPZBJhjOiZzbqYBJeYLiEYPGKPxUgqLvx6tjcN1cUjrXqzpQiG7Iu60yv9t/8/sAbnLhLgUD9yaJkISC4Wvv+lsBSpaRDgeECUdbpjync2o7YseEVepSjHQixxwfvaiSKfXBL8EQWozGQMj3SOAcMOGRqBeOCYe9AMRlrOvO4ZYPPfeXMCpAkjsWqwSXII9ctm+Si89NsBMpkpBYboyT+y0Tsy88/2sBV4PdtFrgmoCRnSv2CuikAwMjiPz0iR1SHnBMB0eRNL5gySQO3OjNWS858D+wSARmeJ9NM0ElvPEHrXS2Gu3QoN4="
    # GPG_KEY_NAME
    - secure: "xCbuNmnrevpEhLTHUb0MhxHPxQc73IrMQbedfRSG2WdRp8eEQTIuGKK2BlCPzdppp6t8EN0FssGWoJuB3jhT9Y44ETaUj+1PnX/qsQZ33+2fPYrnGDcrlG7NEbg8QSEHmeDlWs7qpA/MrbVWzMFPGTVhngY/VVv3TdaipSvnp4VvXjAygploN6z3sXSUgIngORZB/meASpPj9GM3Za0Y/2SUobpHGD6Aeos2z/QYcimx4EfQJNoCvhw5jWp4VAbpI69NPLljp5mNUI7tmPDYFefbIyFSlCWhm4NSd21448yUek5ke1frpy+XpEhi26ch1oFJOiXOafYjq0l/Q8twmSMcrqsVDxTC4xEmcKJilM9ejOpmJgYLamh0bsZK9pDJ7NyFgx3HYK0elHdTnYWpoLu3rE2LJzllwM/vzj6HyZ2YXwQc4lx1LXLiDcyBTh2SzCjeErAQ1Jvyad4fT2sa5pmeI/1OWwR63edS4eRNIjVPTSh3Oe6lkBoxxsDdqICpnIZkeMkK1Tr4RBrWiJ/1RQd4mPhOjhtbraP8ucLlROWhqZ+xKHGRX8Gb6EVDPhYV+Av6l33hAs4jxuAsP+K9ocus9WEhSqKC0+G+8dK/Kzu+f/TdUVmh77NjIYmS25nP1BNCYxKp2Tqhdg4VjS+6dEPwZAXHaO/vxJJzUiUSBK8="
    # GPG_PASSPHRASE
    - secure: "BqYlLPj48HH6Bi5VPtxyHcidZS9fzB//9v3qXNXA6C+NrvkUqS6OkTvzjJce0cT3ADFUR6wlQgTXIFTRGTXmw+QF0L3pprC54uqi0+epOD4WEYfxzYMf7dQNZJs21oAyTUgzUMDCXFSDaKgpM8kFGjZ1elhkwjmSjHp50dEdhi3g+A/QYyuCzgL4i3aNYiVWIkvH5KQJU3QhNWwRgB7eQKerdDUvtnXGzZQd3xtRt5a0L9pLHwKHk3ZeL9kZG1l7q3fGy9MlJPNE2qyslzmQ7JIVgVDp6zFvUgVPkMYlIhOfVnQ+SUqi0DRgjm/wdfjyb41IpaSccOeAqfdTt10zi9brSNCHnSVts5TMXerOYiuvk9cm/eI2DrhdwsLHVlIGxoPOB6NOLVcYNcX7t8fLqm6waSJG8aaZkSVjzpXbRiP8A7WOfzJu3NkSVOvKYs1m8Z+Z2Xuh8vJ2xEHUaWMNYxjUzB/XljT07YU/I00At/uDAHk3m4VPoa4zyOhrKLva5hF71BMUHej6B6wEe3Q0mhfIpKUrLEsoC4ZO56M34xx0T4q34t4BAUnRb5HRBviTaWbLjzaLACwAuMYWMwFFSvbMDmlAJEeNQszRMGmEWbnferUabqca9gRl6OThEAAb7ce7VNjmERm5fAoH8d3MH/Koz95NRatIMuHr6YxwjPs="
jdk:
  - oraclejdk8
before_script:
  - chmod +x gradlew
install: true
script:
  - ./gradlew test
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    script: ./cd/deploy.sh
    on:
      branch: master
      tags: true
  - provider: releases
    api_key:
      secure: "W1S04Sr7tQa5bfDalj8xJBe7abPDFaR+UarvEh+7EBg8TR8/PmTkpKC+x+piDM7YLu65b9idaYCnN3Zn/RxzAbHFEnsIt9YL1WCx73a6phF5+1f+vrqukQXgSwPGi3j7MK5D0/mQ/Jczleb9grH2JhD0UtMIbyJy6YRENB06/3OratL80HeYxe6+YXUPhz1MbwdyTUSVJ5AyIAYIwRXnJoWepZbOIa7lJak5Rfo3FpZfvs1yqosQUHzTjiOu9zOzC9lZNfOzDdzrRncevvdAqOIcD+3eZlsd/rgXEVuTY0Y/2YiptOauVTE5NoJanfdwGdQJpR3Fba5pTqllEEU6OQDdqRRohDL+Ts9cKGRa+y4mG8CHJzBJgAT2Xct8bzLuyjN868iYX+aFYjYInvZNazNh986BY/9Ny22yqJFPyfgi37tPXbrwrzwpzjy7QRVavX12ozXYv5wGzSX0sbGdmsxPEm9qVs071gcVV33F8b+hlbOo3/2ot93Yy5pZRDzF9f403lyE/Kz8O+LMDDFTzJOYH+ZMTpd3LhZKTONq5Oj0m+nEj+bYIxoNbTVsASDC6qU+6RTkVw3nUUEmdLaHwxkzuj1CjVEyogUu8z3MFtuA9pJbrkwBZhuv9RTQjjv4ApROvNs//OBk9Pz1y9ZQ3egpivG7UkaIzp2XWUJU+EQ="
    file_glob: true
    file:
      - "build/libs/jaxrs-standard-${VERSION}.jar"
      - "build/libs/jaxrs-standard-${VERSION}-javadoc.jar"
      - "build/libs/jaxrs-standard-${VERSION}-sources.jar"
    skip_cleanup: true
    on:
      branch: master
      tags: true